### ISSUE TITLE
Uncaught RequestError

### ISSUE THREAD

**Issue by hufftheweevil** [bdr99/node-mymazda#2]
I'm using this package within [a Node-RED node](https://github.com/hufftheweevil/node-red-contrib-mazda) and the other day my Node-RED got stuck because a RequestError was not caught. I can't seem to reproduce the error now, so it looks like it was a one-time occurrence so far. However, the bigger problem was that it had caused Node-RED to get stuck in a restart loop. I can add a `catch` to my usage, but I'm not sure exactly which call caused it. And perhaps this is something that should be caught at this package's level anyway. But I'm not entirely sure. Here is the stack trace that it did output. Can you spot exactly where this happened?

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
RequestError: getaddrinfo EAGAIN 0cxo7m58.mazda.com
    at ClientRequest.<anonymous> (/config/node-red/node_modules/node-mymazda/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/config/node-red/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Comment by bdr99** [comment]
The error shows that a DNS lookup failed for `0cxo7m58.mazda.com`. This could have been a temporary network outage, but it's hard to tell which exact call would have caused this. This could have happened on any of the calls that communicates with the Mazda server. Because the library is communicating with an external server, there will always be unpredictable errors that could happen. I think it would be best if you added try/catch blocks around all of your calls to the library.
